stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

build backend:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - IbayRunner
  script:
    - ./gradlew assemble

test backend:
  stage: test
  tags:
    - IbayRunner
  script:
    - ./gradlew check

deploy backend:
  stage: deploy
#  only:
#    refs:
#      - master
  tags:
    - IbayRunner
  script:
    - mkdir -p ~/api-deployment # mkdir make folder api-deployment ~/ is under current user directory so for gitlab it would be /home/gitlab/api-deployment
    - rm -rf ~/api-deployment/* # rm remove -rf is recursive files from api-deployment
    - cp -r build/libs/. ~/api-deployment # cp - copy build/libs is where
    - sudo service IbayRunner restart  # this requires sudo rights for gitlab user