stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

build backend:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - IbayRunner
  script:
    - ./gradlew assemble
    - docker build --build-arg JAR_FILE=build/libs/*.jar -t ibay/backend .

test backend:
  stage: test
  tags:
    - IbayRunner
  script:
    - ./gradlew check

deploy backend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - IbayRunner
  script:
    - docker-compose down
    - docker-compose up -d
