app:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/IBayDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345


spring:
  flyway:
    locations: classpath:/db/migration/postgres




