app:
  datasource:
    jdbcUrl: jdbc:postgresql://postgres:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

spring:
  flyway:
    locations: classpath:/db/migration/postgres
  profiles:
    active: "production"




