app:
  datasource:
    jdbcUrl: jdbc:postgresql://db:5436/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin


spring:
  flyway:
    locations: classpath:/db/migration/postgres
  profiles:
    active: "production"




